[project]
name = "suvarna-prashan-backend"
version = "0.1.0"
description = "Billing backend for Samarth Shishu Shikshan Samiti"
authors = [
    { name = "Aarsh Bharat", email = "aarshbharat@gmail.com" }
]
requires-python = ">=3.14"

dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.12",
    "sqlalchemy>=2.0.52",
]